{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tunnel-operator.serviceAccountName" . }}
  namespace: {{ include "tunnel-operator.namespace" . }}
  labels: {{- include "tunnel-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
