---
# Source: tunnel-operator/templates/monitor/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tunnel-operator
  namespace: tunnel-system
  labels:
    app.kubernetes.io/name: tunnel-operator
    app.kubernetes.io/instance: tunnel-operator
    app.kubernetes.io/version: "0.17.0"
    app.kubernetes.io/managed-by: kubectl
spec:
  
  clusterIP: None
  
  ports:
    - name: metrics
      port: 80
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: tunnel-operator
    app.kubernetes.io/instance: tunnel-operator
