---
apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
  labels:
    app.kubernetes.io/name: tunnel-operator
    app.kubernetes.io/instance: tunnel-operator
    app.kubernetes.io/version: "0.16.0-rc"
    app.kubernetes.io/managed-by: kubectl
