{{- if not .Values.tunnel.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-operator-tunnel-config
  namespace: {{ include "tunnel-operator.namespace" $ }}
  labels: {{- include "tunnel-operator.labels" $ | nindent 4 }}
data:
  {{- with .Values.tunnel.githubToken }}
  tunnel.githubToken: {{ . | b64enc | quote }}
  {{- end }}
  {{- if or (eq .Values.tunnel.mode "ClientServer") .Values.operator.builtInTunnelServer }}
  {{- with .Values.tunnel.serverToken }}
  tunnel.serverToken: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.tunnel.serverCustomHeaders }}
  tunnel.serverCustomHeaders: {{ . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.operator.builtInTunnelServer }}
  {{- with .Values.tunnel.githubToken }}
  GITHUB_TOKEN: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.tunnel.serverToken }}
  TUNNEL_TOKEN: {{ . | b64enc | quote }}
  {{- end }}
  TUNNEL_USERNAME: {{ .Values.tunnel.serverUser  | b64enc | quote }}
  TUNNEL_PASSWORD: {{ .Values.tunnel.serverPassword  | b64enc | quote }}
  {{- end }}
{{- end }}