{{- if not .Values.trivy.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-operator-trivy-config
  namespace: {{ include "tunnel-operator.namespace" $ }}
  labels: {{- include "tunnel-operator.labels" $ | nindent 4 }}
data:
  {{- with .Values.trivy.githubToken }}
  trivy.githubToken: {{ . | b64enc | quote }}
  {{- end }}
  {{- if or (eq .Values.trivy.mode "ClientServer") .Values.operator.builtInTrivyServer }}
  {{- with .Values.trivy.serverToken }}
  trivy.serverToken: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.trivy.serverCustomHeaders }}
  trivy.serverCustomHeaders: {{ . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.operator.builtInTrivyServer }}
  {{- with .Values.trivy.githubToken }}
  GITHUB_TOKEN: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.trivy.serverToken }}
  TRIVY_TOKEN: {{ . | b64enc | quote }}
  {{- end }}
  TRIVY_USERNAME: {{ .Values.trivy.serverUser  | b64enc | quote }}
  TRIVY_PASSWORD: {{ .Values.trivy.serverPassword  | b64enc | quote }}
  {{- end }}
{{- end }}