apiVersion: v1
kind: Service
metadata:
  name: {{ include "tunnel-operator.fullname" . }}
  namespace: {{ include "tunnel-operator.namespace" . }}
  labels: {{- include "tunnel-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.service.headless }}
  clusterIP: None
  {{ end }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector: {{- include "tunnel-operator.selectorLabels" . | nindent 4 }}
